  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - 3000:11434
    volumes:
      - ./ollama:/root/.ollama
      - ./ownModels:/root/.ollama/models/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
